### ISSUE TITLE
Unknown module prelude when installing via cargo-install

### ISSUE THREAD

**Issue by irevoire** [sharkdp/numbat#165]
Hey!

When installing numbat with `cargo install` we then can't run anything because it’s missing its prelude:
```
% numbat 1
error: while resolving imports in
  ┌─ <input>:1:5
  │
1 │ use prelude
  │     ^^^^^^^ Unknown module

Make sure that you have properly set up Numbat's module path.
Interpreter error in Prelude code
```

Do you think it would be doable to shove all the prelude directly in the binary? 🤔

**Comment by irevoire** [comment]
> Including everything in the binary is definitely possible. This is what we do for the [WASM version](https://numbat.dev/), albeit in a very [hacky way](https://github.com/sharkdp/numbat/blob/master/numbat-wasm/src/wasm_importer.rs) for the moment.

Yeah tbh I was expecting something similar to what you did for the wasm, or [using a crate](https://docs.rs/rust-embed/latest/rust_embed/trait.RustEmbed.html) to hide the « hacky stuff » (is there really any other way to do it?)

> The question is: is this what we want? My

Well, I’m not a maintainor or anything, just someone who used **a lot** insect.sh and was happy to discover that you wrote a new version running on rust.
So, obviously, you get to choose how you want to see the project evolve in the end 😅
But, as a dumb user, what I can say is that I was happy to share with my colleagues and friends that we finally got a cli version that’s easy to install (we're all doing rust). And I find the installation a bit « complex » with the prelude to import somewhere else (basically, you need to read the doc vs a simple install) and I still don't get how to make it work on macOS because it just ignore the `~/.config/numbat` 🥺 

> My original idea was to have the "Numbat standard library" available as files on the user's machine, for easy inspection, extension, and potentially even modification.

Also, about that, I’m wondering what is the best approach. If everyone copy-paste the lib in their local dir, then there is a good chance that they never update it and thus get an outdated stdlib.
In [helix](https://github.com/helix-editor/helix/) they have a similar problem and instead of recommending you to copy/paste their `runtime` directory, IIRC they tell you to simlink it to their repo and `git pull` it when you want to update the editor.

Thanks for the awesome project, now that a version exists in rust I might contribute to it 🔥

**Comment by sharkdp** [comment]
Thanks for being insistent. This should now be fixed, and I agree that the situation for users is much better. And the situation for developers is not worse (it's slightly more complicated to understand what's going on though).

You should now be able to do `cargo install numbat-cli`.

> or [using a crate](https://docs.rs/rust-embed/latest/rust_embed/trait.RustEmbed.html) to hide the « hacky stuff »

Oh, thank you for mentioning that! This worked out nicely. Also for the wasm version.

> and I still don't get how to make it work on macOS because it just ignore the `~/.config/numbat` 🥺

I documented it here: https://numbat.dev/doc/cli-customization.html#config-path — it's not that relevant anymore, since modules are now inside the binary. But it would actually be good to hear if that folder works for `init.nbt`-customization. And if Numbat works on macOS at all :smile:.

> Also, about that, I’m wondering what is the best approach. If everyone copy-paste the lib in their local dir, then there is a good chance that they never update it and thus get an outdated stdlib.

:+1: I have now added instructions for developers in the README. And clarified the documentation [here](https://numbat.dev/doc/cli-customization.html#custom-modules) for users, so that there shouldn't be any problems, unless someone starts to actively modify the prelude.

> Thanks for the awesome project, now that a rust version exists I might contribute to it 🔥

Thank you very much for the feedback. Seeing what you work on (professionally and in your personal projects) you would definitely be more than qualified to work on the Numbat compiler/interpreter! In fact, having the possibility to attract contributors was one of the main factors to rewrite Numbat in Rust. The PureScript community was just too small for that.
