### ISSUE TITLE
Enhanced help output

### ISSUE THREAD

**Issue by eminence** [sharkdp/numbat#238]
Now that we have additional metadata (via 9921465f53c72200dad2043b4d8e112b9b59155c) and a new help command (via #222) maybe we can combine them :)

Here's an example for how an enhanced `help(electronvolt)` might look:

```
>>> help(electronvolt)

Electronvolt
https://en.wikipedia.org/wiki/Electronvolt
Aliases: electronvolts, eV
A unit of [Energy]

  = 1.602176634e-19 joule [Energy]
```

We don't currently have metadata on constants, but maybe we could also imagine a yet further extension:

```
# The Planck constant 
@name("Planck Constant")
@url("https://en.wikipedia.org/wiki/Planck_constant")
let planck_constant: Action = 6.62607015e-34 J / Hz
let ℎ = planck_constant
```

```
>>> help(ℎ)

Plank Constant
https://en.wikipedia.org/wiki/Planck_constant
A unit of [Action]

   =  6.62607015e-34 J / Hz [Action]
```

**Comment by sharkdp** [comment]
Thank you for the feedback. Great idea!

I think I would change the syntax to just `help electronvolt` because `help` is really a command (handled by the CLI or WebInterface directly), and not actual Numbat syntax. You couldn't use it in a Numbat program.




> We don't currently have metadata on constants, but maybe we could also imagine a yet further extension:

Yes, I thought about that as well. We should definitely allow some of the decorators to also be usable on constants. `@aliases` also makes sense on constants. This would allow us to associate `planck_constant` with `ℎ` directly:
```
# The Planck constant 
@name("Planck Constant")
@url("https://en.wikipedia.org/wiki/Planck_constant")
@aliases(ℎ)
let planck_constant: Action = 6.62607015e-34 J / Hz
```
