### ISSUE TITLE
why is creating a function that has raising a power in it so complicated? 

### ISSUE THREAD

**Issue by DEMONhacker404** [sharkdp/numbat#411]
here's a sample of me trying to create a simple pow function, only to be getting thrown at by the parser with meaningless logs
![Screenshot_1464](https://github.com/sharkdp/numbat/assets/77447359/8a311eb1-101d-4bc3-8922-140134767c1d)

**Comment by sharkdp** [comment]
`->` specifies the return type. You are missing an equal sign:
```
fn pow(a: Scalar, p: Scalar) = a^p
```


The error message is not great here, I agree. The problem is this: what you typed in is actually reasonable syntax for a function without a body (FFI function). It's only the "return type" (`a^p`) that can not be parsed. Something like `a^2` would be a proper return type (if `a` were a type). But `a^p` is never allowed. Hence the error.

**Comment by DEMONhacker404** [comment]
thank you!
