### ISSUE TITLE
Support for multi-line functions

### ISSUE THREAD

**Issue by irevoire** [sharkdp/numbat#509]
Hey, I’ve been using numbat more and more and being able to use multi-line functions would _really_ help.
I looked for issue on the subject but didn’t find any, would this be allowed if I made a PR?

And can we use `{}` like we do with structures?

**Comment by sharkdp** [comment]
> being able to use multi-line functions would _really_ help

Yes. This is why I pinned ticket #201. I personally would really like to have what I proposed in https://github.com/sharkdp/numbat/issues/201#issuecomment-2174088579. Is there anything else you would want from "multi line" functions? For now, Numbat functions are pure, so the body is always an expression.. not a sequence of statements.

> And can we use `{}` like we do with structures?

This would make sense if we allow `let`-style bindings. Something like
```
fn f(x, y) {
  let z = x^2 + y^2
  sqrt(z)
}
```

For now, I personally prefer what I proposed in the reference ticket above:
```
fn f(x, y) = sqrt(z)
  where z = x^2 + y^2
```

But I also have to admit that I typed `{` a few times when I wanted to create a Numbat function. I'm open to discussing this.

**Comment by irevoire** [comment]
> For now, Numbat functions are pure, so the body is always an expression.. not a sequence of statements.

Yep, that’s perfect. I don’t think we need anything else.

About this:
> Concerning the syntax, I would personally favor the let … in … syntax for [let-expressions](https://en.wikipedia.org/wiki/Let_expression) that seems common in other programming languages (Haskell) and the literature.
> But what I would like even more is the … where … syntax that is also used in functional programming languages, because it puts the important things first and reads a bit more naturally. It also extends more nicely to a multi-definition version:

Personally, I think I would prefer the `let ... in` statements, especially when there are conditionals going on:
```haskell
fn truc(n) = if m < 0
        then n
        else m
    where m = n / 2
```

vs

```ocaml
fn truc(n) =
    let m = n / 2 in
    if m < 0
        then n
        else m
```

imo it's easier to follow what's going on.

BUT, whatever you prefer I may have a bit of time to work on it next week

**Comment by sharkdp** [comment]
> Is there a reason, though, for not having a sequence of statements?

Mostly simplicity of the grammar. And also the pureness property.  `<expr> where [list of bindings]` or `let [list of bindings] in <expr>` would still be an expression. Something like `{ print("hello"); <return-expr> }` is not an expression. And it's not a pure function due to the side effects.

That said, we did break the pureness/referential transparency property with the `rand` and `error` functions though, so maybe we need to sacrifice this anyway.

> I feel like it could make sense to call procedures before returning your value, for example:

Yes, I agree. That might be useful.

> Personally, I think I would prefer the `let ... in` statements, especially when there are conditionals going on:

I think it comes down to personal preference. I like the `… where …` syntax in more mathematically-oriented code since it shows the most important part first (which expression do we return) before listing the details (what kind of helper variables do we need to write that expression in a nice way). I also think it looks nicer if there are multiple local definitions.

But a lot of functional programming languages support both `… where …` and `let … in …`, so it's not unreasonable to do the same in Numbat. I would start with the `where` syntax and we can add `let-in` later. What do you think?

**Comment by sharkdp** [comment]
> BUT, whatever you prefer I may have a bit of time to work on it next week

Sounds great! The parsing part is hopefully straightforward. We can do local variables only at first. Local functions first require support for closures (#347). Let me know if you need support with the typechecker/type-inference part. Also, not that there is a working (but slightly outdated) implementation in #201 (https://github.com/sharkdp/numbat/issues/201#issuecomment-2173237749).
