### ISSUE TITLE
Cannot find quadratic_equation on numbat.dev

### ISSUE THREAD

**Issue by deepakjois** [sharkdp/numbat#602]
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/67fb108d-2ba7-4832-ba95-9ab238226bd4">

**Comment by sharkdp** [comment]
You need to import `extra::algebra` to use this function (https://numbat.dev/doc/list-functions-math.html?highlight=quadra#algebra)

```
use extra::algebra
```

**Comment by deepakjois** [comment]
Thanks! I suspected I wasnt importing something. But I couldnt find the `use` keyword anywhere even after skimming the docs multiple times. Maybe worth putting this info somewhere in the docs where it can be found easily?

**Comment by deepakjois** [comment]
[This place](https://numbat.dev/doc/cli-customization.html?highlight=use#custom-modules) may be a bit too obscure, and i initially thought it might be for custom modules that we write and not for modules that are available by default

**Comment by Goju-Ryu** [comment]
It might be a good idea in general to explicitly tell if a module is auto imported or if you should `use` it first. I imagine a single line under the
> Defined in: `extra::algebra`

Maybe something like:
> requires using: `use extra::algebra`

It would require some changes to the build script in book, but I wouldn't mind taking a stab at it if you agree that something like this would be beneficial.

**Comment by Goju-Ryu** [comment]
An alternative approach I just thought of that would be much easier is to just change the sidebar so that it contains prelude modules as a subcategory of [The prelude](https://numbat.dev/doc/prelude.html) and all other predefined functions stay as a subcategory of [Predefined functions](https://numbat.dev/doc/predefined-functions.html), which then just gets a bit descriptive text about how to use the modules found there. It's much easier, probably more intuitive and would avoid repeating basically the same line everywhere.

**Comment by sharkdp** [comment]
> [This place](https://numbat.dev/doc/cli-customization.html?highlight=use#custom-modules) may be a bit too obscure, and i initially thought it might be for custom modules that we write and not for modules that are available by default

True. Let's improve this.

> requires using: `use extra::algebra`

I have another idea. Since #566 has been merged, we now have example code for every function Numbat. See https://numbat.dev/doc/list-functions-math.html?highlight=quadra#quadratic_equation-solve-quadratic-equations, for example. Maybe we should add `use extra::algebra` as an additional line to the examples that require it?

**Comment by Goju-Ryu** [comment]
> Maybe we should add `use extra::algebra` as an additional line to the examples that require it?

I like that way of doing it. It keeps it close to the function and makes it obvious how the example was able to call the it.
